<?php
declare(strict_types=1);
require __DIR__ . '/relay.php';
header('Cache-Control: no-store'); header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");
header('X-Content-Type-Options: nosniff');
if (is_file(__DIR__ . '/config.php')) { http_response_code(403); exit('نصب انجام شده است. تنظیمات را در config.php ویرایش کنید و installer.php را حذف کنید.'); }
$https = !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off';
if (!$https && !in_array($_SERVER['REMOTE_ADDR'] ?? '', ['127.0.0.1','::1'], true)) { http_response_code(403); exit('ابتدا HTTPS دامنه را فعال کنید.'); }
session_start(['cookie_httponly'=>true, 'cookie_secure'=>$https, 'cookie_samesite'=>'Strict']);
$_SESSION['csrf'] ??= bin2hex(random_bytes(32));
function esc(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
$error = ''; $success = false;
$ready = version_compare(PHP_VERSION, '8.1', '>=') && extension_loaded('curl') && is_writable(__DIR__);
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if (!hash_equals($_SESSION['csrf'], (string)($_POST['csrf'] ?? ''))) throw new RuntimeException('صفحه را تازه کنید و دوباره تلاش کنید.');
        if (!isset($_SESSION['authorized'])) {
            $keyFile = __DIR__ . '/setup-key.php';
            $key = is_file($keyFile) ? require $keyFile : '';
            if (!is_string($key) || strlen($key) < 24 || str_contains($key, 'REPLACE_') || !hash_equals($key, (string)($_POST['key'] ?? ''))) throw new RuntimeException('کلید نصب صحیح نیست؛ setup-key.php را مطابق راهنما بسازید.');
            session_regenerate_id(true); $_SESSION['authorized'] = true;
        } elseif (($_POST['action'] ?? '') === 'review') {
            if (!$ready) throw new RuntimeException('پیش‌نیازهای PHP، cURL و مجوز نوشتن را بررسی کنید.');
            $mode = (string)($_POST['mode'] ?? '');
            $config = relay_config([
                'public_url' => trim((string)($_POST['public_url'] ?? '')), 'mode' => $mode,
                'panels' => ['marzban'=>trim((string)($_POST['marzban'] ?? '')), 'pasarguard'=>trim((string)($_POST['pasarguard'] ?? ''))],
                'order' => $mode === 'dual' ? ['marzban','pasarguard'] : [$mode],
                'connect_timeout' => (int)($_POST['connect_timeout'] ?? 5), 'timeout' => (int)($_POST['timeout'] ?? 20),
            ]);
            $checks = [];
            foreach ($config['order'] as $panel) {
                $probe = relay_request($config['panels'][$panel] . '/subrelay-install-probe-' . bin2hex(random_bytes(12)), $config, ['User-Agent: SubRelay-Installer/0.1']);
                if ($probe['error'] || $probe['status'] >= 300 && $probe['status'] < 400 || $probe['status'] >= 500) throw new RuntimeException('اتصال یا TLS پنل ' . $panel . ' مشکل دارد؛ آدرس نهایی /sub و پورت خروجی را بررسی کنید.');
                $checks[$panel] = $probe['status'];
            }
            $_SESSION['pending'] = $config; $_SESSION['checks'] = $checks;
        } elseif (($_POST['action'] ?? '') === 'save') {
            if (!isset($_SESSION['pending'])) throw new RuntimeException('ابتدا تنظیمات را بررسی کنید.');
            $config = relay_config($_SESSION['pending']);
            $lock = fopen(__DIR__ . '/install.lock', 'c');
            if (!$lock || !flock($lock, LOCK_EX)) throw new RuntimeException('قفل نصب ایجاد نشد.');
            try {
                if (file_exists(__DIR__ . '/config.php')) throw new RuntimeException('تنظیمات قبلاً ایجاد شده‌اند.');
                $file = fopen(__DIR__ . '/config.php', 'x');
                if (!$file) throw new RuntimeException('امکان ساخت config.php نیست.');
                $data = "<?php\n// Generated by SubRelay. Edit this file to change relay settings.\nreturn " . var_export($config, true) . ";\n";
                $written = fwrite($file, $data); fclose($file);
                if ($written !== strlen($data)) { unlink(__DIR__ . '/config.php'); throw new RuntimeException('ذخیره تنظیمات کامل نشد.'); }
                chmod(__DIR__ . '/config.php', 0600);
                $success = true; $_SESSION = []; session_destroy();
            } finally { flock($lock, LOCK_UN); fclose($lock); }
        } elseif (($_POST['action'] ?? '') === 'edit') { unset($_SESSION['pending']); }
    } catch (Throwable $e) { $error = $e->getMessage(); }
}
?>
<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>نصب SubRelay</title>
<style>*{box-sizing:border-box}body{margin:0;background:#081421;color:#dce8f3;font:16px/1.9 Tahoma,Arial,sans-serif;min-height:100vh;display:grid;place-items:center;padding:28px}main{width:min(100%,720px);background:#102235;border:1px solid #29465c;border-radius:24px;padding:32px;box-shadow:0 30px 90px #0005}h1{margin:0;color:#5ee6c3}h2{font-size:20px}p{color:#b5c8d9}label{display:block;margin-top:15px}input,select{width:100%;padding:12px;border-radius:10px;border:1px solid #36556c;background:#081421;color:white;font:inherit}input{direction:ltr;text-align:left}button{margin-top:22px;padding:12px 24px;border:0;border-radius:10px;background:#5ee6c3;color:#081421;font:inherit;cursor:pointer}code{direction:ltr;unicode-bidi:embed;color:#7ce5cf;overflow-wrap:anywhere}.notice{padding:15px;background:#19334a;border-radius:12px}.error{color:#ffb4b4}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:520px){main{padding:22px}.grid{grid-template-columns:1fr}}.muted{font-size:13px}</style>
<main><h1 dir="ltr">SubRelay</h1><p>نصب واسط اشتراک مرزبان و پاسارگارد روی هاست ایران</p>
<?php if ($error): ?><p class="notice error"><?=esc($error)?></p><?php endif; ?>
<?php if ($success): ?>
<h2>تنظیمات ذخیره شد</h2><p>فایل <code>config.php</code> کنار <code>index.php</code> ساخته شد. برای تغییر دامنه، پنل‌ها و زمان انتظار، همین فایل را از File Manager ویرایش کنید.</p>
<p class="notice"><code><?=esc($config['public_url'])?>/sub/USER_TOKEN</code></p><p>آدرس عمومی را در پنل‌ها تنظیم کنید. سپس لینک واقعی را با مرورگر و چند کلاینت تست کنید.</p><p>نصب‌کننده قفل شده است؛ اکنون <code>installer.php</code>، <code>setup-key.php</code> و <code>install.lock</code> را حذف کنید.</p>
<?php elseif (!isset($_SESSION['authorized'])): ?>
<h2>۱. ورود به نصب</h2><p>روی یک زیردامنه اختصاصی با HTTPS نصب کنید. محتویات پوشه <code>src/</code> باید در ریشه همان زیردامنه باشد؛ فایل مخفی <code>.htaccess</code> را هم منتقل کنید.</p><p>از فایل‌های قبلی بکاپ بگیرید. فایل <code>setup-key.example.php</code> را به <code>setup-key.php</code> کپی کنید و مقدار آن را به یک کلید تصادفی اختصاصی با حداقل ۲۴ کاراکتر تغییر دهید.</p>
<form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><label>کلید نصب<input type="password" name="key" required autocomplete="off"></label><button>ورود</button></form>
<?php elseif (isset($_SESSION['pending'])): $pending=$_SESSION['pending']; ?>
<h2>۳. تأیید نهایی</h2><p>تنها فایل جدید <code>config.php</code> ساخته می‌شود. نصب‌کننده فایل‌های قبلی را بازنویسی نمی‌کند.</p><p>حالت: <code><?=esc($pending['mode'])?></code><br>دامنه عمومی: <code><?=esc($pending['public_url'])?></code></p>
<?php foreach($pending['order'] as $panel): ?><p><code><?=esc($panel)?>: <?=esc($pending['panels'][$panel])?></code><br>پاسخ بررسی اتصال: HTTP <?=esc($_SESSION['checks'][$panel])?></p><?php endforeach; ?>
<p>زمان اتصال: <?=esc($pending['connect_timeout'])?> ثانیه؛ زمان کل هر پنل: <?=esc($pending['timeout'])?> ثانیه</p>
<p class="notice">این بررسی با توکن آزمایشی انجام شد و اعتبار لینک واقعی یا عملکرد صفحه ساب را تأیید نمی‌کند. در حالت مشترک، فقط HTTP 404 باعث بررسی پاسارگارد می‌شود.</p>
<form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><button name="action" value="save">تأیید و ذخیره</button> <button name="action" value="edit">ویرایش</button></form>
<?php else: ?>
<h2>۲. تنظیمات اتصال</h2><p class="notice">PHP 8.1+: <?=version_compare(PHP_VERSION,'8.1','>=')?'✓':'✗'?> · cURL: <?=extension_loaded('curl')?'✓':'✗'?> · نوشتن فایل: <?=is_writable(__DIR__)?'✓':'✗'?></p>
<form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="action" value="review">
<label>نوع فوروارد<select name="mode"><option value="marzban">فقط مرزبان</option><option value="pasarguard">فقط پاسارگارد</option><option value="dual">هر دو — مرزبان سپس پاسارگارد</option></select></label>
<label>دامنه عمومی<input type="url" name="public_url" placeholder="https://sub.example.com" required></label><p class="muted">فقط آدرس زیردامنه؛ بدون /sub در انتها.</p>
<label>آدرس اشتراک مرزبان<input type="url" name="marzban" placeholder="https://marzban.example.com/sub"></label>
<label>آدرس اشتراک پاسارگارد<input type="url" name="pasarguard" placeholder="https://pasarguard.example.com/sub"></label><p class="muted">آدرس پنل همراه مسیر واقعی اشتراک و در صورت نیاز پورت، بدون توکن کاربر. فقط پنل‌های حالت انتخابی لازم هستند.</p>
<div class="grid"><label>زمان اتصال (ثانیه)<input type="number" name="connect_timeout" value="5" min="1" max="120" required></label><label>زمان کل هر درخواست<input type="number" name="timeout" value="20" min="1" max="120" required></label></div>
<p>در حالت مشترک توکن‌های دو پنل باید متفاوت باشند. خطاهای اتصال، TLS و سرور باعث امتحان پنل دوم نمی‌شوند.</p><p>این پروژه اشتراک و HTML صفحه ساب را منتقل می‌کند. ترافیک VPN به آدرس‌های داخل کانفیگ متصل می‌شود.</p><button>بررسی اتصال و نمایش خلاصه</button></form>
<?php endif; ?></main></html>
